name: irecovery CI

on:
  workflow_dispatch:
  push:
    paths:
      - "**.rs"
      - "**.toml"
      - "**.yml"
  pull_request:
    paths:
      - "**.rs"
      - "**.toml"
      - "**.yml"

jobs:
  test-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --all-features

      - name: Build
        run: cargo build --all-targets --all-features
